
name: HCL DevOps Test UI

on: workflow_dispatch

jobs:
    UI-Action:
        runs-on: self-hosted
        name: HCL DevOps Test UI
        steps:
         - name: Execute Test
           uses: LekyaS/FTGithubActionTest@main
           with:
            projectDirectory: C:\Users\preethi.as\Documents\WorkSpace-2024\Project1
            scriptName: Script1
